const user = [
  {
    id: "1",
    Name: "Reem Saeed",
    JobTitle: "Admin",
    Salary: "9500 SR",
    ContractValidity: "2years",
    userId: "1",
    email: "rreemsaeed5@gmail.com",
    password: "123366",
    Tell: "054445588 ",
    role: "Admin",
    isAdmin: true,
  },
  {
    id: "2",
    Name: "Mohammed",
    JobTitle: "boss",
    Salary: "15000 SR",
    ContractValidity: "2years",
    userId: "2",
    email: "Mohammed@gmail.com",
    password: "258258",
    Tell: "055558888 ",
    role: "Boss",
    isBoss: true,
  },
  {
    id: "3",
    Name: "mona",
    LastName: "Ahmad",
    JobTitle: "employ",
    Salary: "6500 SR",
    ContractValidity: "2years",
    userId: "3",
    email: "Mona@gmail.com",
    password: "123456",
    Tell: " 055444444",
    role: "Employ",
    isUser: true,
  },
  {
    id: "4",
    Name: "sara",
    LastName: "Ahmad",
    JobTitle: "employ",
    Salary: "6500 SR",
    ContractValidity: "2years",
    userId: "4",
    email: "sara@gmail.com",
    password: "123456",
    Tell: " 05544444555",
    role: "Employ",
    isUser: true,
  },
];

module.exports = { user };
